#!/bin/sh
# Place the script to the root path of ABCL.

# Detect whether Java is available on your system.
if ! command -v java -version 2>/dev/null 1>&2;
then
  echo "No Java on your system" >&2;
  exit 1;
fi

# Locate the path of the script itself.
root=$(dirname "$0");

# Run ABCL.
java -jar "$root/abcl.jar" --eval "(require :abcl-contrib)" "$@";
