#!/bin/sh
# Place the script to the root path of ABCL.

# Detect whether Java is available on your system.
if ! command -v java -version 2>/dev/null 1>&2;
then
  echo "No Java on your system" >&2;
  exit 1;
fi

# Locate the path of the script itself.
root=$(dirname "$0");

# Check whether some Lisp script is available.
script=$1;

if [ -f "$script" ];
then
  # Consume the first argument.
  shift;

  java -jar "$root/abcl.jar" --noinform --eval "(require :abcl-contrib)" --load "$script" "$@";
else
  java -jar "$root/abcl.jar" --eval "(require :abcl-contrib)" "$@";
fi
