#!/bin/sh
# Place the script to the root path of Clozure CL.

if [ "Linux" = $(uname) ];
then
  if [ "x86_64" = $(uname -m) ];
  then
    ccl="lx86cl64";
  else
    ccl="lx86cl";
  fi
elif [ "Darwin" = $(uname) ];
then
  if [ "x86_64" = $(uname -m) ];
  then
    ccl="dx86cl64";
  else
    ccl="dx86cl";
  fi
elif [ "FreeBSD" = $(uname) ];  # Untested
then
  if [ "x86_64" = $(uname -m) ];
  then
    ccl="fx86cl64";
  else
    ccl="fx86cl";
  fi
elif [ "SunOS" = $(uname) ];  # Untested
then
  if [ "x86_64" = $(uname -m) ];
  then
    ccl="sx86cl64";
  else
    ccl="sx86cl";
  fi
else
  echo "Unsupported platform" >&2;
  exit 1;
fi

root=$(dirname "$0");

script=$1;

if [ -z "$script" ] || [ ! -f "$script" ];
then
  echo "Not a valid Lisp script" >&2;
  exit 1;
fi

# Consume first argument.
shift;

"$root/$ccl" -l "$script" "$@";
