#!/bin/sh

# The script assumes that SBCL is in system path.

# Check whether SBCL is available.
if ! command -v sbcl 2>/dev/null 1>&2;
then
  echo "Please install SBCL" >&2;
  exit 1;
fi

# Check whether the Lisp script is available.
script=$1;

if [ -z "$script" ] || [ ! -f "$script" ];
then
  echo "Not a valid Lisp script";
  exit 1;
fi

# Consume first argument.
shift;

# Run SBCL with UTF-8 external format in batch mode.
sbcl --noinform --eval "(setf sb-impl::*default-external-format* :UTF-8)" --script "$script" "$@";
